### ISSUE TITLE
SSML Fails on v1beta1

### ISSUE THREAD

**Issue by thomasf1** [googleapis/python-texttospeech#334] opened 2022-09-24 21:11 UTC
Based on the example, once I switched the SynthesisInput from text (working) to ssml (even with the most basic) syntax, I do get an InvalidArgument error.

The ssml works in the online demo (https://cloud.google.com/text-to-speech#all-features). 
#### Environment details

Running on colab. Works with the text input.

#### Steps to reproduce

  1.  Run it 
 
#### Code example

```python
from google.cloud import texttospeech_v1beta1

# Create a client
client = texttospeech_v1beta1.TextToSpeechClient()

# Initialize request argument(s)
input = texttospeech_v1beta1.SynthesisInput()
#input.text = text
input.ssml = '''<speak>Hey</speak>'''

voice = texttospeech_v1beta1.VoiceSelectionParams()
voice.language_code = "en-US"
voice.name = 'Neural2-A'

audio_config = texttospeech_v1beta1.AudioConfig()
audio_config.audio_encoding = "MP3"
audio_config.pitch = -5
audio_config.speaking_rate = 1.4
# Does not work???
#audio_config.effects_profile_id = 'handset-class-device'

request = texttospeech_v1beta1.SynthesizeSpeechRequest(
    input=input,
    voice=voice,
    audio_config=audio_config,
)

# Make the request
response = client.synthesize_speech(request=request)
print(response)
```

#### Stack trace
```
InvalidArgument: 400 Request contains an invalid argument.
```

**Comment by thomasf1** [comment] 2022-09-24 21:12
PS: Unrelated but funny: With one of my ssml files, I have completely broken the online demo (https://cloud.google.com/text-to-speech#all-features). Only strange babbling comes out.

https://user-images.githubusercontent.com/937467/192118936-9cbcc28c-4ac0-49f1-9d9e-d3fb756acc0f.mov

**Comment by parthea** [comment] 2023-09-22 11:15
Using the sample code provided, I was able to re-create the `400 Request contains an invalid argument` error.

```
google.api_core.exceptions.InvalidArgument: 400 Voice 'Neural2-A' does not exist. Is it misspelled? [detail: "[ORIGINAL ERROR] generic::invalid_argument: Voice \'Neural2-A\' does not exist. Is it misspelled? [google.rpc.error_details_ext] { message: \"Voice \\\'Neural2-A\\\' does not exist. Is it misspelled?\" }"
```

The error with the latest version of the client library appears to include more verbose information to help identify the issue.

The issue is that `Neural2-A`  should be of the values [here](https://cloud.google.com/text-to-speech/docs/voices), such as `en-US-Neural2-A`

```
from google.cloud import texttospeech_v1beta1

# Create a client
client = texttospeech_v1beta1.TextToSpeechClient()

# Initialize request argument(s)
input = texttospeech_v1beta1.SynthesisInput()
#input.text = text
input.ssml = '''<speak>Hey</speak>'''

voice = texttospeech_v1beta1.VoiceSelectionParams()
voice.language_code = "en-US"
voice.name = 'en-US-Neural2-A'

audio_config = texttospeech_v1beta1.AudioConfig()
audio_config.audio_encoding = "MP3"
audio_config.pitch = -5
audio_config.speaking_rate = 1.4
# Does not work???
#audio_config.effects_profile_id = 'handset-class-device'

request = texttospeech_v1beta1.SynthesizeSpeechRequest(
    input=input,
    voice=voice,
    audio_config=audio_config,
)

# Make the request
response = client.synthesize_speech(request=request)
print(response)
```

I'm going to close this issue as resolved but please feel free to open a new issue.

**Closed by parthea** 2023-09-22 11:15 UTC
Labels: api: texttospeech, type: question
